services:
  notebook:
    image: ghcr.io/gluzzati/product-design-gpt-jtbd:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
      - ./.env:/app/.env